name: uploader
description: This package is used for creating AAB/APK and IPA files, and sending them to Play Console, TestFlight, and Firebase App Distribution
version: 0.0.7
homepage: https://github.com/emircetn/uploader

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ^2.0.2
  collection: ^1.17.2
  yaml: ^3.1.2
  googleapis_auth: ^1.4.1
  googleapis: ^11.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
