name: Bump version and create tag

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create new tag
      uses: projectsyn/pr-label-tag-action@v1
